### PR TITLE
Fix type bug + update to PHP 7.4+

### LINKED ISSUE #5989: [BUG] news feeds will not be updated automatically
Hi,

I have the following error:
After updating to FreshRSS 1.23.0, the news feeds will not be updated automatically.
Hosted on a server (PHP 8.2), I start a php script via cron job:
```

<?php
exec("/usr/bin/php app/actualize_script.php 2>&1", $out, $result);
echo "Return code: " .$result ."<br>";
echo "Script output: " ."<br>";
echo "<pre>"; print_r($out);
?>

```

This should start the php script in the /app/.... directory (the php script is there unchanged from the installation). This worked without any problems up to version 1.22.1.

I use FreshRSS with the “Fiery Feeds” app (iOS 17.2.1), which has also updated without any problems and displayed current feeds.
The feeds can only be updated manually on the server.

**To Reproduce**
1. Update to 1.23.0
2. use Cronjob (like described) to start update-php

**Expected behavior**
As in the previous versions, the php script should update the news feeds every 20 minutes (cron job execution rhythm).

**Environment information (please complete the following information):**
- Device: iPhone 14 Pro
- OS: iOS 17.2.1
- Browser: Safari, Firefox
- FreshRSS version: 1.23.0
- Database version: SQLite
- PHP version: PHP 8.2
- Installation type: all-inkl.com

### PR DESCRIPTION
**Pull request by Alkarex**
Related to https://github.com/FreshRSS/Extensions/pull/185
fix https://github.com/FreshRSS/FreshRSS/issues/5989#issuecomment-1872530041

### CODE REVIEW

File: extension.php [hunk 1]
```diff
@@ -1,34 +1,41 @@
...
-    
-    public function handleConfigureAction() {
+
+    public function handleConfigureAction(): void {
         $this->registerTranslates();
 
         if (Minz_Request::isPost()) {
             $configuration = [
-                'patterns' => Minz_Request::paramTextToArray('patterns', ''),
+                'patterns' => Minz_Request::paramTextToArray('patterns', []),
```
Comment (Alkarex) [inline extension.php:15]: This was the bug

**Review by aledeg — APPROVED** [review]
